version: "3.6"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data
  server:
    image: node
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: npm run dev
  client:
    image: node
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    command: npm run dev

volumes:
  pg-data: {}